# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - sample-application

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "sample-application"
  DOTNET_VERSION: "8.0"
  NODE_VERSION: "20.x"
  SOLUTION_PATH: "SampleExercise.sln"
  SERVER_PROJECT_PATH: "SampleExercise.Server/SampleExercise.Server.csproj"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Restore solution dependencies
        run: dotnet restore "${{ env.SOLUTION_PATH }}"

      - name: Build entire solution (includes client build via MSBuild)
        run: dotnet build "${{ env.SOLUTION_PATH }}" --configuration Release --no-restore

      - name: Test solution
        run: dotnet test "${{ env.SOLUTION_PATH }}" --configuration Release --no-build --verbosity normal

      - name: Publish server project (includes client assets)
        run: dotnet publish "${{ env.SERVER_PROJECT_PATH }}" --configuration Release --no-build --output ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_31919EB9B8C34FB9A345FAA75D9D4EB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_43272FD5F83048B4B4616CE28B559735 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_647257BA34D84EEF9CF8C5A97A03DD60 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "sample-application"
          slot-name: "Production"
          package: .
